[project]
name = "flyrank-internship"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.0",
    "huggingface-hub>=0.24",
    "ipykernel>=7.3.0",
    "matplotlib>=3.8",
    "numpy>=1.26",
    "pandas>=2.2",
    "reportlab>=4.0",
    "scikit-learn>=1.4",
    "seaborn>=0.13.2",
]
